# Generated by Django 3.2 on 2021-12-16 01:52

import application.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dtm', models.DateTimeField(auto_now_add=True)),
                ('updated_dtm', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bill',
                'get_latest_by': 'created_dtm',
            },
        ),
        migrations.CreateModel(
            name='ConsigneeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('contact', models.BigIntegerField()),
                ('gstin', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=300)),
                ('created_dtm', models.DateTimeField(auto_now_add=True)),
                ('updated_dtm', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Consignee',
                'get_latest_by': 'created_dtm',
            },
        ),
        migrations.CreateModel(
            name='ConsignorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('contact', models.BigIntegerField()),
                ('gstin', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=300)),
                ('created_dtm', models.DateTimeField(auto_now_add=True)),
                ('updated_dtm', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Consignor',
                'get_latest_by': 'created_dtm',
            },
        ),
        migrations.CreateModel(
            name='DriverModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('contact_number', models.BigIntegerField(default=None)),
                ('alternate_contact', models.BigIntegerField(default=None)),
                ('family_contact', models.BigIntegerField(default=None)),
                ('date_of_joining', models.DateField(default=None)),
                ('license_number', models.CharField(max_length=45)),
                ('license_document', models.FileField(upload_to=application.models.user_directory_path)),
                ('address_permanent', models.CharField(default=None, max_length=300)),
                ('address_temporary', models.CharField(default=None, max_length=300)),
                ('created_dtm', models.DateTimeField(auto_now_add=True)),
                ('updated_dtm', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Driver',
                'ordering': ['name'],
                'get_latest_by': 'created_dtm',
            },
        ),
        migrations.CreateModel(
            name='LoadingChallanModel',
            fields=[
                ('lc_no', models.AutoField(primary_key=True, serialize=False)),
                ('billing_date', models.DateField(default=None)),
                ('place_of_receipt', models.CharField(default='Coimbatore', max_length=45)),
                ('place_of_delivery', models.CharField(choices=[('indore', 'Indore'), ('nagpur', 'Nagpur'), ('pune', 'Pune'), ('secunderabad', 'Secunderabad')], default=None, max_length=45)),
                ('supplier', models.CharField(max_length=45)),
                ('weight', models.CharField(max_length=45)),
                ('vehicle_hire', models.IntegerField()),
                ('advance_amount', models.IntegerField()),
                ('balance_amount', models.IntegerField()),
                ('created_dtm', models.DateTimeField(auto_now_add=True)),
                ('updated_dtm', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.drivermodel')),
            ],
            options={
                'db_table': 'LoadingChallan',
                'get_latest_by': 'created_dtm',
            },
        ),
        migrations.CreateModel(
            name='TruckModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_number', models.CharField(max_length=45)),
                ('no_of_wheels', models.IntegerField(default=None)),
                ('model', models.IntegerField(default=None)),
                ('feet', models.IntegerField(default=None)),
                ('mileage', models.IntegerField(default=None)),
                ('manufacture_name', models.CharField(max_length=45)),
                ('manufacture_date', models.DateField(default=None)),
                ('truck_type', models.CharField(max_length=45)),
                ('tonnage', models.CharField(max_length=300)),
                ('created_dtm', models.DateTimeField(auto_now_add=True)),
                ('updated_dtm', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Truck',
                'ordering': ['truck_number'],
                'get_latest_by': 'created_dtm',
            },
        ),
        migrations.CreateModel(
            name='ShippingOrdersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignor_gst', models.CharField(max_length=15)),
                ('consignor_place', models.CharField(default='Coimbatore', max_length=15)),
                ('consignee_gst', models.CharField(max_length=15)),
                ('consignee_place', models.CharField(choices=[('indore', 'Indore'), ('nagpur', 'Nagpur'), ('pune', 'Pune'), ('secunderabad', 'Secunderabad')], default=None, max_length=15)),
                ('no_of_packages', models.CharField(max_length=15)),
                ('package_value', models.IntegerField()),
                ('package_description', models.CharField(max_length=115)),
                ('actual_weight', models.IntegerField()),
                ('charged_weight', models.IntegerField()),
                ('freight_charges', models.IntegerField()),
                ('lr_charges', models.IntegerField()),
                ('hamali_charges', models.IntegerField()),
                ('door_collection', models.IntegerField()),
                ('door_delivery', models.IntegerField()),
                ('other_charges', models.IntegerField()),
                ('total_charges', models.IntegerField()),
                ('paid_amount', models.IntegerField()),
                ('payment_status', models.CharField(choices=[('to_pay', 'To Pay'), ('tbb', 'To be Billed'), ('paid', 'PAID')], default=None, max_length=20)),
                ('invoice_no', models.IntegerField()),
                ('invoice_date', models.DateField(default=None)),
                ('billing_date', models.DateField(default=None)),
                ('gs_tax_payable', models.CharField(choices=[('Consignee', 'Consignee'), ('Consignor', 'Consignor'), ('IPL', 'IPL')], default=None, max_length=20)),
                ('created_dtm', models.DateTimeField(auto_now_add=True)),
                ('updated_dtm', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.billmodel')),
                ('consignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.consigneemodel')),
                ('consignor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.consignormodel')),
                ('loading_challan', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.loadingchallanmodel')),
            ],
            options={
                'db_table': 'Orders',
                'get_latest_by': 'created_dtm',
            },
        ),
        migrations.AddField(
            model_name='loadingchallanmodel',
            name='vehicle_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.truckmodel'),
        ),
        migrations.AddField(
            model_name='billmodel',
            name='consignor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.consignormodel'),
        ),
    ]
