# Generated by Django 3.2 on 2021-12-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadingchallanmodel',
            name='advance_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='loadingchallanmodel',
            name='balance_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='shippingordersmodel',
            name='actual_weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='shippingordersmodel',
            name='charged_weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='shippingordersmodel',
            name='door_collection',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='shippingordersmodel',
            name='door_delivery',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='shippingordersmodel',
            name='freight_charges',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='shippingordersmodel',
            name='hamali_charges',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='shippingordersmodel',
            name='lr_charges',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='shippingordersmodel',
            name='other_charges',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='shippingordersmodel',
            name='paid_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='shippingordersmodel',
            name='total_charges',
            field=models.FloatField(),
        ),
    ]
