# Generated by Django 3.2 on 2021-12-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20211217_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingordersmodel',
            name='door_collection',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='shippingordersmodel',
            name='door_delivery',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='shippingordersmodel',
            name='freight_charges',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='shippingordersmodel',
            name='hamali_charges',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='shippingordersmodel',
            name='lr_charges',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='shippingordersmodel',
            name='other_charges',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
