# Generated by Django 3.2 on 2021-12-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20211217_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadingchallanmodel',
            name='weight',
            field=models.IntegerField(max_length=45),
        ),
    ]
