# Generated by Django 3.2 on 2021-12-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_loadingchallanmodel_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckmodel',
            name='mileage',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='truckmodel',
            name='model',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='truckmodel',
            name='tonnage',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='truckmodel',
            name='truck_type',
            field=models.CharField(choices=[('open', 'Open'), ('close', 'Close')], default=None, max_length=45),
        ),
    ]
