# Generated by Django 3.2 on 2021-12-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_alter_truckmodel_mileage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consigneemodel',
            old_name='contact',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='consignormodel',
            old_name='contact',
            new_name='contact_number',
        ),
        migrations.AlterField(
            model_name='truckmodel',
            name='mileage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
