# Generated by Django 3.2 on 2021-12-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_auto_20211219_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingordersmodel',
            name='package_value',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
