# Generated by Django 3.2 on 2021-12-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_alter_shippingordersmodel_package_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingordersmodel',
            name='gs_tax_payable',
            field=models.CharField(choices=[('Consignee', 'Consignee'), ('Consignor', 'Consignor'), ('IPL', 'IPL')], default=None, max_length=45),
        ),
        migrations.AlterField(
            model_name='shippingordersmodel',
            name='invoice_no',
            field=models.CharField(max_length=45),
        ),
    ]
