# Generated by Django 3.2 on 2021-12-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_alter_drivermodel_family_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentNotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sent', models.DateTimeField(default=False)),
            ],
            options={
                'db_table': 'payment_notification',
                'get_latest_by': 'date',
            },
        ),
        migrations.AlterField(
            model_name='shippingordersmodel',
            name='package_description',
            field=models.CharField(max_length=1000),
        ),
    ]
