# Generated by Django 3.2 on 2022-01-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_auto_20211226_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashReceiptsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gc_no', models.CharField(max_length=45)),
                ('received_from', models.CharField(max_length=125)),
                ('receipt_date', models.DateField(default=None)),
                ('booked_from', models.CharField(max_length=125)),
                ('booked_to', models.CharField(max_length=125)),
                ('total_amount', models.FloatField()),
                ('created_dtm', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cash_receipts',
            },
        ),
    ]
