# Generated by Django 3.2 on 2022-01-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_cashreceiptsmodel_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingordersmodel',
            name='amount_per_kg',
            field=models.FloatField(default=None, null=True),
        ),
    ]
