# Generated by Django 3.2 on 2022-01-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_shippingordersmodel_amount_per_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consigneemodel',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='consignormodel',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
