# Generated by Django 3.2 on 2022-01-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_auto_20220130_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashreceiptsmodel',
            name='gc_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cashreceiptsmodel',
            name='payment_status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='drivermodel',
            name='license_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='drivermodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='loadingchallanmodel',
            name='place_of_delivery',
            field=models.CharField(choices=[('indore', 'Indore'), ('nagpur', 'Nagpur'), ('pune', 'Pune'), ('secunderabad', 'Secunderabad')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='loadingchallanmodel',
            name='place_of_receipt',
            field=models.CharField(default='Coimbatore', max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingordersmodel',
            name='consignee_place',
            field=models.CharField(choices=[('indore', 'Indore'), ('nagpur', 'Nagpur'), ('pune', 'Pune'), ('secunderabad', 'Secunderabad')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingordersmodel',
            name='consignor_place',
            field=models.CharField(default='Coimbatore', max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingordersmodel',
            name='gs_tax_payable',
            field=models.CharField(choices=[('Consignee', 'Consignee'), ('Consignor', 'Consignor'), ('IPL', 'IPL')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingordersmodel',
            name='invoice_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingordersmodel',
            name='no_of_packages',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='truckmodel',
            name='manufacture_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='truckmodel',
            name='model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='truckmodel',
            name='truck_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='truckmodel',
            name='truck_type',
            field=models.CharField(choices=[('open', 'Open'), ('close', 'Close')], default=None, max_length=100),
        ),
    ]
