# Generated by Django 3.2 on 2021-12-20 14:57

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('account', '0002_ipluser_is_secondaryuser'), ('account', '0003_alter_ipluser_created_dtm')]

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipluser',
            name='is_secondaryUser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ipluser',
            name='created_dtm',
            field=models.DateTimeField(default=account.models.get_now, verbose_name='Created'),
        ),
    ]
