# Generated by Django 3.2 on 2021-12-20 10:28

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_ipluser_is_secondaryuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipluser',
            name='created_dtm',
            field=models.DateTimeField(default=account.models.get_now, verbose_name='Created'),
        ),
    ]
